---
title: "Billigence1"
output:
  pdf_document: default
  html_document: default
date: "2024-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }

library(dplyr)
library(tidyverse)
library(lubridate)
library(tidyr)
library(skimr)
library(ggplot2)
library(mlbench)
library(gmodels)
library(class)
library(knitr)


```


```{r}

#reading the client dataset
client_df<-read.csv("Data.csv")

#checking first 6 entries 
head(client_df)

#smmarising
summary(client_df)



```
```{r}

#renaming the column "y" to "State" 
#which describes whether the customer said 'yes' or 'no' to the deposit

client_df <- client_df %>% 
       rename("state" = "y")
head(client_df)

```

Here the goal is to determine whether the customer will say yes to deposit. Since the dataset is large I will be focussing majorily on customers who said yes. And try to find any relation or pattern among the customers. So in future the bank could focus on marketing among such customers.

```{r, 'filter'}
# 
# #filtering 
# 
df_state_yes<-filter(client_df,state=="yes")
head(df_state_yes)

```

```{r}

unique(client_df$state)

#remove empty string values form state column
client_df <- subset(client_df, state != " ")

unique(client_df$state)



ggplot(data = client_df, aes(x = state, y = duration, fill = state, colour = state)) + 
  geom_bar(stat = "identity") 
 



```

```{r}


#Relationship between Campaign and Status
ggplot(data=client_df, aes(x = state,y= campaign , colour = state)) + 
  geom_bar(stat = "identity")

```


```{r}

#Relationship between Marital status and Age

ggplot(df_state_yes)+
  geom_point(mapping = aes(x=marital,y=age) ,color="blue")



```


```{r}



# Calculate the count of 'yes' status for each occupation
occupation_counts <- client_df %>%
  filter(state == 'yes') %>%
  group_by(job) %>%
  summarise(YesCount = n()) %>%
  arrange(YesCount)  # Arrange in descending order of 'yes' count

# Reorder the 'job' variable based on the count of 'yes' status
client_df$job <- factor(client_df$job, levels = occupation_counts$job)

# Plot the graph with occupations sorted in descending order of 'yes' status
ggplot(data = client_df) +
  geom_bar(mapping = aes(y = job, fill = state), color = "blue") +
  theme(legend.position = "bottom") +
  labs(x = "Relationship between Occupation and Statu", title = "Occupation")



```


```{r}


# Plot the graph with occupations sorted in descending order of 'yes' status
ggplot(data = client_df) +
  geom_bar(mapping = aes(y = job, fill = state), color = "blue") +  # Swapping x and y
  theme(axis.text.y = element_text(angle = 45, hjust = 1), legend.position = "bottom") +  # Adjusting y-axis text
  labs(y = "Occupation", title = "Relationship between Occupation and Status")  # Changing y-axis label


```



```{r}


#Relationship between Education and Status

ggplot(data=client_df)+
  geom_bar(mapping = aes(x = education,fill=state))+ 
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "Relationship between Education and Status")


```


```{r}

#Relationship between Loan and Status

ggplot(data=client_df)+
  geom_bar(mapping = aes(x = loan,fill=state))+ 
  labs(title = "Relationship between Loan and Status")




```


```{r}


day_hist <- ggplot(df_state_yes, aes(day))
day_hist + geom_area(stat = "bin", color = "black",fill = "slateblue1", alpha = 0.5) + theme(text = element_text(size=30))



```

```{r}

conversionsAgeMarital <- df_state_yes %>%
  group_by(AgeGroup = cut(age, breaks = seq(20, 70, by = 10)),
           Marital = marital) %>%
  summarize(Count = n(), 
            NumConversions = sum(ifelse(state == "yes", 1, 0))) %>%
  mutate(TotalCount = sum(Count),
         ConversionRate = NumConversions / TotalCount * 100)

# Print the intermediate steps to debug
print(conversionsAgeMarital)

kable(conversionsAgeMarital)



#rename the last groups
conversionsAgeMarital$AgeGroup <- as.character(conversionsAgeMarital$AgeGroup)
conversionsAgeMarital$AgeGroup[is.na(conversionsAgeMarital$AgeGroup)] <- "70+"

#visualizing conversions by age group and marital status
ggplot(conversionsAgeMarital, aes(x=AgeGroup, y=ConversionRate, fill=Marital)) +
  geom_bar(width=0.5, stat = "identity") +
  labs(title="Conversion Rates by Age Group and Marital Status") +
  theme( legend.position = 'bottom')

```


```{r}


# Filter data for each marital status
married_data <- conversionsAgeMarital %>% filter(Marital == "married")
single_data <- conversionsAgeMarital %>% filter(Marital == "single")
divorced_data <- conversionsAgeMarital %>% filter(Marital == "divorced")



#MARRIED
# Sort the data for married individuals by ConversionRate in descending order
married_data_sorted <- married_data %>%
  arrange(desc(ConversionRate))

# Reorder levels of AgeGroup based on ConversionRate
married_data_sorted$AgeGroup <- factor(married_data_sorted$AgeGroup, 
                                       levels = married_data_sorted$AgeGroup)

# Function to customize theme
custom_theme <- function() {
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "bottom")
}

# Plot for married individuals with reordered levels of AgeGroup
ggplot(married_data_sorted, aes(x = AgeGroup, y = ConversionRate)) +
  geom_bar(stat = "identity", fill = "lightblue", width = 0.5) +
  labs(title = "Conversion Rates by Age Group for Married Individuals") +
  facet_wrap(~Marital) +
  custom_theme()



#SINGLE

# Sort the data for single individuals by ConversionRate in descending order
single_data_sorted <- single_data %>%
  arrange(desc(ConversionRate))

# Reorder levels of AgeGroup based on ConversionRate
single_data_sorted$AgeGroup <- factor(single_data_sorted$AgeGroup, 
                                       levels = single_data_sorted$AgeGroup)



# Plot for married individuals with reordered levels of AgeGroup
ggplot(single_data_sorted, aes(x = AgeGroup, y = ConversionRate)) +
  geom_bar(stat = "identity", fill = "lightgreen", width = 0.5) +
  labs(title = "Conversion Rates by Age Group for Single Individuals") +
  facet_wrap(~Marital) +
  custom_theme()


#DIVORCED

# Sort the data for single individuals by ConversionRate in descending order
divorced_data_sorted <- divorced_data %>%
  arrange(desc(ConversionRate))

# Reorder levels of AgeGroup based on ConversionRate
divorced_data_sorted$AgeGroup <- factor(divorced_data_sorted$AgeGroup, 
                                       levels = divorced_data_sorted$AgeGroup)



# Plot for married individuals with reordered levels of AgeGroup
ggplot(divorced_data_sorted, aes(x = AgeGroup, y = ConversionRate)) +
  geom_bar(stat = "identity", fill = "salmon", width = 0.5) +
  labs(title = "Conversion Rates by Age Group for Divorced Individuals") +
  facet_wrap(~Marital) +
  custom_theme()


```



```{r}


client_df$month <- factor(client_df$month, levels = c("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec")) # Sort by chronological month order

month_bar <- ggplot(client_df, aes(month, fill = state)) +
  geom_bar(color = "black") + 
  theme(text = element_text(size = 30), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 30))

month_bar



```

```{r}


df_state_yes$month <- factor(df_state_yes$month,levels = c("jan", "feb", "mar", "apr","may", "jun", "jul", "aug","sep", "oct", "nov", "dec")) #sort by chronological month order
month_bar <- ggplot(df_state_yes, aes(month))
month_bar + geom_bar(color = "black",fill = "gold") +  theme(text = element_text(size=30), axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1,size=30))


```

```{r}


df_state_no <- filter(client_df,state=="no")
head(df_state_no)


df_state_no$month <- factor(df_state_no$month,levels = c("jan", "feb", "mar", "apr","may", "jun", "jul", "aug","sep", "oct", "nov", "dec")) #sort by chronological month order
month_bar <- ggplot(df_state_no, aes(month))
month_bar + geom_bar(color = "black",fill = "gold") +  theme(text = element_text(size=30), axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1,size=30))


```



